ergoplatform/ergo-appkit

docs/things-to-do-blog-post.md

Did heavy editing, with a couple small section rewrites.
Also I added a new title that is a bit more enticing from a marketing standpoint so people understand what Appkit does/why it's important. Feel free not to use the title, but thought I'd throw it in too.

Heavy Editing Of Appkit Blogpost

---

appkit/src/test/scala-2.12/VerifiedContractsSpec.scala
appkit/src/test/scala/org/ergoplatform/appkit/AnonimousAccessSpec.scala
appkit/src/test/scala/org/ergoplatform/appkit/ApiClientSpec.scala
appkit/src/test/scala/org/ergoplatform/appkit/examples/RunMockedScala.scala
build.sbt
common/src/main/java/org/ergoplatform/appkit/ErgoId.java
common/src/main/java/org/ergoplatform/appkit/ErgoTreeTemplate.java
common/src/main/java/org/ergoplatform/appkit/ErgoType.java
common/src/main/java/org/ergoplatform/appkit/JavaHelpers.scala
common/src/test/scala/org/ergoplatform/appkit/package.scala
java-client-generated/src/main/java/org/ergoplatform/explorer/client/TransactionsApi.java
lib-api/src/main/java/org/ergoplatform/appkit/BlockchainContext.java
lib-api/src/main/java/org/ergoplatform/appkit/BoxOperations.java
lib-api/src/main/java/org/ergoplatform/appkit/InputBox.java
lib-api/src/main/java/org/ergoplatform/appkit/OutBoxBuilder.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/BlockchainContextImpl.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/ExplorerFacade.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/InputBoxImpl.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/OutBoxBuilderImpl.java

https://github.com/ScorexFoundation/sigmastate-interpreter/pull/617
Todo:

Use verified contracts from sigmastate's formal verification branch

---

lib-api/src/main/java/org/ergoplatform/appkit/BoxOperations.java

skip boxes with tokens if token is not asked in BoxOperations.selectTop;

---

lib-api/src/main/java/org/ergoplatform/appkit/OutBoxBuilder.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/OutBoxBuilderImpl.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/UnsignedTransactionBuilderImpl.java

for https://github.com/aslesarenko/ergo-tool/pull/35

add OutBoxBuilder.mintToken

---

.editorconfig
.gitignore
build.sbt
common/src/main/java/org/ergoplatform/appkit/JavaHelpers.scala
lib-api/src/main/java/org/ergoplatform/appkit/BoxOperations.java
lib-api/src/main/java/org/ergoplatform/appkit/BoxSelectorsJavaHelpers.scala
lib-impl/src/main/java/org/ergoplatform/appkit/impl/UnsignedTransactionBuilderImpl.java

ergo PR - https://github.com/ergoplatform/ergo/pull/1071
Todo:

switch BoxOperations.selectTop to use wallets BoxSelectors.select;

---

appkit/src/test/scala/org/ergoplatform/appkit/JavaHelpersSpec.scala
build.sbt

- Update CDN Typesafe maven releases (#58)
- Update sigma dependency to v3.3.1 (#59)
Contributors: @zargarzadehm @aslesarenko

Release v3.3.1 (with Sigma v3.3.1)

---

appkit/src/test/scala/org/ergoplatform/appkit/ChangeOutputSpec.scala
appkit/src/test/scala/org/ergoplatform/appkit/JavaHelpersSpec.scala
build.sbt
common/src/main/java/org/ergoplatform/appkit/JavaHelpers.scala
lib-api/src/main/java/org/ergoplatform/appkit/SignedTransaction.java
lib-api/src/main/java/org/ergoplatform/appkit/UnsignedTransactionBuilder.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/UnsignedTransactionBuilderImpl.java

- Token burning (#61)
See this [test as a usage example](https://github.com/ergoplatform/ergo-appkit/blob/6947718e81fc3fe60a89befd66ca325d6e2178c3/appkit/src/test/scala/org/ergoplatform/appkit/ChangeOutputSpec.scala#L171)

Release v3.3.2 (with Sigma v3.3.1 and ergo-wallet v3.3.3)

---

appkit/src/test/scala/org/ergoplatform/appkit/MultiProveDHT.scala
appkit/src/test/scala/org/ergoplatform/appkit/MultiProveDlog.scala
lib-impl/src/main/java/org/ergoplatform/appkit/impl/ErgoProverBuilderImpl.java

- Throw IllegalStateException on duplicate secrets
- Add support for multiple dlog and DHT secrets
Contributors: @scalahub

Ergo Appkit v3.3.3 (with Sigma v3.3.1 and ergo-wallet v3.3.3)

---

appkit/src/test/scala/org/ergoplatform/appkit/ChangeOutputSpec.scala
appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala
common/src/main/java/org/ergoplatform/appkit/AppkitProvingInterpreter.scala
common/src/main/java/org/ergoplatform/appkit/ContextVar.java
common/src/main/java/org/ergoplatform/appkit/ExtendedInputBox.scala
common/src/main/java/org/ergoplatform/appkit/JavaHelpers.scala
common/src/test/scala/org/ergoplatform/appkit/AppkitTesting.scala
lib-api/src/main/java/org/ergoplatform/appkit/InputBox.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/ErgoProverImpl.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/InputBoxImpl.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/UnsignedTransactionBuilderImpl.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/UnsignedTransactionImpl.java

Context variables

---

appkit/src/test/scala/org/ergoplatform/appkit/ChangeOutputSpec.scala
appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala
common/src/main/java/org/ergoplatform/appkit/AppkitProvingInterpreter.scala
common/src/main/java/org/ergoplatform/appkit/ContextVar.java
common/src/main/java/org/ergoplatform/appkit/ErgoValue.java
common/src/main/java/org/ergoplatform/appkit/ExtendedInputBox.scala
common/src/main/java/org/ergoplatform/appkit/JavaHelpers.scala
common/src/test/scala/org/ergoplatform/appkit/AppkitTesting.scala
common/src/test/scala/org/ergoplatform/appkit/ErgoValueSpec.scala
lib-api/src/main/java/org/ergoplatform/appkit/InputBox.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/ErgoProverImpl.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/InputBoxImpl.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/UnsignedTransactionBuilderImpl.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/UnsignedTransactionImpl.java

In this PR:
- new method ErgoValue.fromHex 
- each InputBox can be extended with context variables (see withContextVars method)

Release v4.0.1 (with Sigma v4.0.1 and ergo-wallet v4.0.0)

---

appkit/src/main/java/org/ergoplatform/appkit/RestApiErgoClient.java
appkit/src/main/java/org/ergoplatform/appkit/config/ErgoNodeConfig.java
appkit/src/test/scala/org/ergoplatform/appkit/AnonymousAccessSpec.scala
appkit/src/test/scala/org/ergoplatform/appkit/FileMockedErgoClient.java
appkit/src/test/scala/org/ergoplatform/appkit/HttpClientTesting.scala
appkit/src/test/scala/org/ergoplatform/appkit/cli/CommandsTesting.scala
lib-api/src/main/java/org/ergoplatform/appkit/ErgoClient.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/BlockchainContextBuilderImpl.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/BlockchainContextImpl.java

Work without explorer

---

appkit/src/test/scala/org/ergoplatform/appkit/AnonymousAccessSpec.scala
lib-api/src/main/java/org/ergoplatform/appkit/BlockchainContext.java
lib-api/src/main/java/org/ergoplatform/appkit/BoxOperations.java
lib-api/src/main/java/org/ergoplatform/appkit/CoveringBoxes.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/BlockchainContextImpl.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/ExplorerFacade.java

Collection of CoveringBoxes using chunked requests

---

appkit/src/test/scala/org/ergoplatform/appkit/MnemonicSpec.scala
common/src/main/java/org/ergoplatform/appkit/Mnemonic.java
common/src/main/java/org/ergoplatform/appkit/MnemonicValidationException.java

Add Mnemonic.toEntropy and Mnemonic.checkEnglishMnemonic to validate mnemonics for  MrStahlfelge/ergo-wallet-android#8
Hope I got Scala formatting right!

Add Mnemonic.toEntropy and Mnemonic.checkEnglishMnemonic

---

build.sbt
common/src/main/java/org/ergoplatform/appkit/AppkitProvingInterpreter.scala
common/src/main/java/org/ergoplatform/appkit/JavaHelpers.scala
lib-impl/src/main/java/org/ergoplatform/appkit/impl/BlockchainContextImpl.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/ErgoNodeFacade.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/SignedTransactionImpl.java

Follow-up to ScorexFoundation/sigmastate-interpreter#736

Java7 compatibility

---

appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala
common/src/main/java/org/ergoplatform/appkit/ContextVar.java
common/src/main/java/org/ergoplatform/appkit/ErgoType.java
common/src/main/java/org/ergoplatform/appkit/ErgoValue.java
common/src/main/java/org/ergoplatform/appkit/JavaHelpers.scala
common/src/test/scala/org/ergoplatform/appkit/AppkitTestingCommon.scala

Pass Box value as context variable and register

---

lib-impl/src/main/java/org/ergoplatform/appkit/impl/BlockchainContextImpl.java
lib-impl/src/test/java/org/ergoplatform/appkit/impl/BlockchainContextImplTest.java

Avoid error "There should be no duplicate inputs" when sending funds

---

appkit/src/test/scala/org/ergoplatform/appkit/ApiClientSpec.scala
appkit/src/test/scala/org/ergoplatform/appkit/JavaHelpersSpec.scala
build.sbt
common/src/main/java/org/ergoplatform/appkit/JavaHelpers.scala
common/src/main/java/org/ergoplatform/appkit/Mnemonic.java
common/src/main/java/org/ergoplatform/appkit/SecretStorage.java
common/src/main/java/org/ergoplatform/appkit/SecretString.java

Use latest release of ergo-wallet and sigmastate-interpreter
(Follow-up to #100)

Updated sigmastate-interpreter to 4.0.5, updated ergo-wallet to 4.0.20

---

lib-impl/src/main/java/org/ergoplatform/appkit/impl/ScalaBridge.scala
lib-impl/src/test/java/org/ergoplatform/appkit/impl/ScalaBridgeTest.scala

Include Context variables in toJson method

---

appkit/src/test/resources/mockwebserver/node_responses/response_NodeInfo.json
common/src/main/java/org/ergoplatform/appkit/NetworkType.java
java-client-generated/src/main/java/org/ergoplatform/restapi/client/NodeInfo.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/BlockchainContextImpl.java

I noticed that connected on the wrong API port is not detected by appkit and added a check.

Check if reported network type matches given network type

---

appkit/src/test/scala/org/ergoplatform/appkit/AddressSpec.scala
appkit/src/test/scala/org/ergoplatform/appkit/AnonymousAccessSpec.scala
appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala
common/src/main/java/org/ergoplatform/appkit/Address.java
common/src/main/java/org/ergoplatform/appkit/ErgoContract.java
common/src/main/java/org/ergoplatform/appkit/impl/ErgoScriptContract.java
common/src/main/java/org/ergoplatform/appkit/impl/ErgoTreeContract.java
lib-api/src/main/java/org/ergoplatform/appkit/BoxOperations.java

This one is called a lot within the project and in client projects, so a helper method is justified.

Add Address.getErgoContract convenience method

---

appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala
java-client-generated/src/main/java/org/ergoplatform/explorer/client/model/TransactionInfo1.java
lib-api/src/main/java/org/ergoplatform/appkit/ReducedTransaction.java
lib-api/src/main/java/org/ergoplatform/appkit/SignedTransaction.java
lib-api/src/main/java/org/ergoplatform/appkit/Transaction.java
lib-api/src/main/java/org/ergoplatform/appkit/UnsignedTransaction.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/OutBoxImpl.scala
lib-impl/src/main/java/org/ergoplatform/appkit/impl/ReducedTransactionImpl.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/SignedTransactionImpl.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/UnsignedTransactionImpl.java

Some smaller improvements, additionally changes TransactionInfo1 inclusionHeight to Long to get it future proof.

Introduce Transaction interface, fix Java 7 compability

---

common/src/main/java/org/ergoplatform/appkit/SelectTokensHelper.java
lib-api/src/main/java/org/ergoplatform/appkit/CoveringBoxes.java
lib-impl/src/test/java/org/ergoplatform/appkit/impl/BlockchainContextImplTest.java

 Fix CoveringBoxes.isCovered() only takes erg into account not tokens

---

java-client-generated/src/main/java/org/ergoplatform/restapi/client/NodeInfo.java
java-client-generated/src/main/java/org/ergoplatform/restapi/client/Peer.java

This adds restApiUrl from ergoplatform/ergo#1652 and updates outdated information.

NodeInfoApi and node PeerApi, updated and restApiUrl added

---

build.sbt

Fix RoboVM incompatibility in sigmastate

---

appkit/src/test/scala/org/ergoplatform/appkit/ErgoValueTest.java
common/src/main/java/org/ergoplatform/appkit/ErgoValue.java
common/src/main/java/org/ergoplatform/appkit/JavaHelpers.scala

This adds method to use `Coll` more easily from Java

Add methods to construct Coll from Java and use in ErgoValue more easy

---

java-client-generated/src/main/java/org/ergoplatform/restapi/client/TransactionsApi.java

No tests added as these endpoints are not supported by most nodes out there (yet)

New TransactionsApi endpoints added in ergoplatform/ergo#1869

---

appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala
appkit/src/test/scala/org/ergoplatform/appkit/examples/DataInputsSpec.scala
lib-api/src/main/java/org/ergoplatform/appkit/BoxOperations.java
lib-api/src/main/java/org/ergoplatform/appkit/UnsignedTransactionBuilder.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/UnsignedTransactionBuilderImpl.scala

Add methods addInputs(), addOutputs(), addDataInputs(), inputs()

UnsignedTransactionBuilder add methods

---

lib-api/src/main/java/org/ergoplatform/appkit/babelfee/BabelFeeBoxState.java
lib-api/src/main/java/org/ergoplatform/appkit/babelfee/BabelFeeOperations.java

* Babel fee EIP accepted
* Best price of a fee box is the highest price per token, not the lowest

Babelfee bestprice

---

MIGRATION
appkit/src/main/scala/org/ergoplatform/appkit/ColdErgoClient.scala
appkit/src/test/scala/org/ergoplatform/appkit/ErgoAuthSpec.scala
appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala
build.sbt
common/src/main/java/org/ergoplatform/appkit/AppkitProvingInterpreter.scala
common/src/main/java/org/ergoplatform/appkit/JavaHelpers.scala
common/src/main/java/org/ergoplatform/appkit/Parameters.java
common/src/main/java/org/ergoplatform/appkit/Signature.java
common/src/test/scala/org/ergoplatform/appkit/ErgoTreeTemplateSpec.scala
common/src/test/scala/org/ergoplatform/appkit/ReducedErgoLikeTransactionSpec.scala
lib-impl/src/main/java/org/ergoplatform/appkit/impl/BlockchainContextBase.java

This PR migrates the appkit code to use sigmastate v5.0

Migrate to sigma v5.0

---

appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala

This demonstrates issue #199 and will be resolved when ScorexFoundation/sigmastate-interpreter#838 is resolved

Test case for issue #199

---

appkit/src/test/scala/org/ergoplatform/appkit/ErgoValueTest.java
appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala
build.sbt
common/src/main/java/org/ergoplatform/appkit/AppkitProvingInterpreter.scala
common/src/main/java/org/ergoplatform/appkit/JavaHelpers.scala
common/src/main/java/org/ergoplatform/appkit/SigmaPropInterpreter.scala
common/src/main/java/org/ergoplatform/appkit/scalaapi/Extensions.scala
common/src/main/java/org/ergoplatform/appkit/scalaapi/Utils.scala
common/src/test/scala/org/ergoplatform/appkit/ReducedErgoLikeTransactionSpec.scala
lib-api/src/main/java/org/ergoplatform/appkit/InputBoxesValidator.scala
lib-impl/src/main/java/org/ergoplatform/appkit/impl/BlockchainContextBase.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/ErgoProverImpl.scala
lib-impl/src/main/java/org/ergoplatform/appkit/impl/NodeAndExplorerDataSourceImpl.java
lib-impl/src/main/java/org/ergoplatform/appkit/impl/ReducedTransactionImpl.java

In this PR:
- fixed ReducedErgoLikeTransaction serializer to store tx cost
- updated Sigma to v5.0.5 and code upgraded

Upgrade to sigma v5.0.5
