build.sbt
Typesafe did migrate to a new CDN lately.
Bintray has a [mirror of maven central](https://dl.bintray.com/typesafe/maven-releases/).
=> Update CDN Typesafe maven releases

appkit/src/test/scala/org/ergoplatform/appkit/ChangeOutputSpec.scala, build.sbt, common/src/main/java/org/ergoplatform/appkit/JavaHelpers.scala, lib-api/src/main/java/org/ergoplatform/appkit/SignedTransaction.java, lib-api/src/main/java/org/ergoplatform/appkit/UnsignedTransactionBuilder.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/UnsignedTransactionBuilderImpl.java
=> Token burning

common/src/main/java/org/ergoplatform/appkit/ErgoTreeTemplate.java, lib-api/src/main/java/org/ergoplatform/appkit/InputBox.java, lib-api/src/main/java/org/ergoplatform/appkit/SignedTransaction.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/InputBoxImpl.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/SignedTransactionImpl.java
=> Add backwards compatible 'formatJson' option to the toJson methods

.gitignore, common/src/main/java/org/ergoplatform/appkit/Parameters.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/UnsignedTransactionBuilderImpl.scala
On testnet, issueing transactions used the wrong fee address causing transactions only get mined if a miner sets minfee to 0. This PR fixes it.
=> Use correct fee address on testnet

build.sbt, common/src/main/java/org/ergoplatform/appkit/InputBoxesSelectionException.java, lib-api/src/main/java/org/ergoplatform/appkit/BoxSelectorsJavaHelpers.scala
For MrStahlfelge/ergo-wallet-android#25
This enables client to access the original error information returned from DefaultBoxSelector by repacking it into objects that Java can handle.
Not sure if my conversion into HashMap is the way to go, if there is a  better way please let me know.
=> Pass-through original DefaultBoxSelector error information

appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala, lib-api/src/main/java/org/ergoplatform/appkit/ErgoProver.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/ErgoProverImpl.scala
https://github.com/ergoplatform/ergo-appkit/issues/65
👋  ErgoTeam,  I took on this issue to get more familiar with the code base.  (tagged as `Good first issue`)
If the code in this PR makes sense I am happy to continue adding the needed unit-tests.
The API side of these changes are made in other PR on the ergo repo: https://github.com/ergoplatform/ergo/pull/1484/files
@aslesarenko I was also wondering if passing a SigmaBoolean makes sense at all. I was thinking on just passing the public key i.e:
```scala
// no tx here
def signMessage(message:  Array[Byte], hintsBag: HintsBag): Array[Byte] = {
pk = _prover.publicKeys.head 
_prover.signMessage(pk, message, hintsBag).getOrThrow
}
```
----
=> Supporting Sigma v4.0.1 signing functions 

lib-api/src/main/java/org/ergoplatform/appkit/BoxOperations.java
Cause: BoxOperations.loadTop for single sender address did not select boxes for tokens properly
=> Fix problem when using BoxOperations.loadTop for single sender address to select token boxes

lib-api/src/main/java/org/ergoplatform/appkit/BlockchainContext.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/BlockchainContextImpl.java, lib-impl/src/test/java/org/ergoplatform/appkit/impl/BlockchainContextImplTest.java
`BlockchainContextImpl.getUnspentBoxesFor` returns a list of unspent boxes. However, when the node it connects to is not in full sync, certain box information can't be retrieved. This causes an NPE and no unspend box can be retrieved.
With this change, instead of throwing an NPE a null object is added to the list. This way, the applications can see that some information is missing (and not confuse a smaller chunk size with the end of the list), but can continue working with other available unspent boxes.
=> BlockchainContextImpl.getUnspentBoxesFor: skip boxes unknown to node

appkit/src/test/scala/org/ergoplatform/appkit/AddressSpec.scala, appkit/src/test/scala/org/ergoplatform/appkit/Bip32SerializationSpec.scala, appkit/src/test/scala/org/ergoplatform/appkit/MnemonicSpec.scala, common/src/main/java/org/ergoplatform/appkit/Address.java, common/src/main/java/org/ergoplatform/appkit/Bip32Serialization.java, common/src/main/java/org/ergoplatform/appkit/JavaHelpers.scala
Also added method  to derive eip3 addresses from such a key
Needed for ergoplatform/ergo-wallet-app#32
=> Add methods to serialize and deserialize an extended public key according to bip-32

java-client-generated/src/main/java/org/ergoplatform/explorer/client/DefaultApi.java, java-client-generated/src/test/java/org/ergoplatform/explorer/client/DefaultApiTest.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/ExplorerFacade.java
ergoplatform/explorer-backend#153 reversed ordering of getApiV1BoxesUnspentByaddressP1, making users spent their newest UTXO instead of their oldest one as before.
New param to configure behaviour was added with ergoplatform/explorer-backend#155
This param is now added here and used to resemble the old behaviour.
=> Explorer API: Add sortDirection to getApiV1BoxesUnspentByaddressP1

appkit/src/test/scala/org/ergoplatform/appkit/AnonymousAccessSpec.scala, appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala, common/src/main/java/org/ergoplatform/appkit/ErgoContract.java, common/src/main/java/org/ergoplatform/appkit/impl/ErgoScriptContract.java, common/src/main/java/org/ergoplatform/appkit/impl/ErgoTreeContract.java, lib-api/src/main/java/org/ergoplatform/appkit/BoxOperations.java, lib-api/src/main/java/org/ergoplatform/appkit/InputBox.java, lib-api/src/main/java/org/ergoplatform/appkit/OutBox.java, lib-api/src/main/java/org/ergoplatform/appkit/UnsignedTransaction.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/BlockchainContextBase.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/InputBoxImpl.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/OutBoxImpl.scala, lib-impl/src/main/java/org/ergoplatform/appkit/impl/UnsignedTransactionBuilderImpl.scala, lib-impl/src/main/java/org/ergoplatform/appkit/impl/UnsignedTransactionImpl.java
Created additional accessor methods in InputBox, OutBox, ErgoContract, and UnsignedTransaction along with their Impl versions. Also replaced token function in OutBox with getTokens() and passed in additional variables when building UnsignedTransactions
=> New Accessor Methods

lib-impl/src/main/java/org/ergoplatform/appkit/impl/UnsignedTransactionImpl.java
👋  I am updating the playground with a SimulatedBlockchainContext. 
having this function as public would let me delete a lot of code.
=> Making  public get unsigne dtx for UnsignedTransactionImpl

appkit/src/test/scala/org/ergoplatform/appkit/MockedBoxesLoader.java, appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala, build.sbt, common/src/main/java/org/ergoplatform/appkit/SelectTokensHelper.java, lib-api/src/main/java/org/ergoplatform/appkit/BoxOperations.java, lib-api/src/main/java/org/ergoplatform/appkit/CoveringBoxes.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/BlockchainContextImpl.java
When we have tokens in selected inboxes that shouldn't be sent, a change box is needed to return the tokens to the sending address. That means that a small amount of ERG is needed on top of the actual amount to send which must be considered when selecting boxes.
This change adds the ability to BoxOperations to account for a change box amount and an accompanying test case. However, the test case files although BoxOperations is now correctly selecting the two boxes of the test case. This is due to `DefaultBoxSelector` ignoring the second, needed box which needs to be fixed in ergo-wallet.
Follow-up to #103
=> BoxOperations: Consider amount for change box

appkit/src/test/scala/org/ergoplatform/appkit/AnonymousAccessSpec.scala, appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala, lib-api/src/main/java/org/ergoplatform/appkit/BoxOperations.java
When I prepared the examples for Ergo Pay, I found myself writing repeating code preparing a transaction with inputs, fee, change box, only differing in the way how outputs are built.
I switched to use a helper method for Ergo Pay example to get rid of the repeating code, and I think it is useful to have it on Appkit for others to use. When found useful and merged, we can use it for adding more logic depending on it like minting a new token.
=> BoxOperations: provide method preparing TransactionBuilder with fee, inputs and change address

common/src/main/java/org/ergoplatform/appkit/ErgoValue.java, common/src/main/java/org/ergoplatform/appkit/JavaHelpers.scala, lib-api/src/main/java/org/ergoplatform/appkit/IErgoBox.java, lib-api/src/main/java/org/ergoplatform/appkit/InputBox.java, lib-api/src/main/java/org/ergoplatform/appkit/OutBox.java, lib-api/src/main/java/org/ergoplatform/appkit/TransactionBox.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/InputBoxImpl.java
This is a set of small additions in preparation of Eip4Token branch.
* `ErgoValue.pairOf` helper was missing
* `collToByteArray`, a Java-friendly way to convert Coll[Byte] to byte[]
* `IErgoBox` super interface for InputBox and Outbox
I am aware that `IErgoBox` does not follow the normal naming style, but `ErgoBox` was not possible as it clashed with ErgoBox.scala - better suggestions welcome
=> Set of small additions

appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala, common/src/main/java/org/ergoplatform/appkit/Signature.java, lib-api/src/main/java/org/ergoplatform/appkit/ErgoProver.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/ErgoProverImpl.scala
verifying a signature is independant from actual prover and doesn't need any secrets, so this changes the code towards being usable without constructing a prover holding secrets.
=> Make verifySignature static on ErgoProver

java-client-generated/src/main/java/org/ergoplatform/explorer/client/DefaultApi.java, java-client-generated/src/test/java/org/ergoplatform/explorer/client/DefaultApiTest.java
This fixes wrong return type for Explorer's getApiV1Blocks
=> Fix Explorer API getApiV1Blocks

MIGRATION, appkit/src/main/java/org/ergoplatform/appkit/RestApiErgoClient.java, java-client-generated/src/main/java/org/ergoplatform/explorer/client/ExplorerApiClient.java, java-client-generated/src/main/java/org/ergoplatform/restapi/client/ApiClient.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/NodeAndExplorerDataSourceImpl.java
This cleans up ExplorerApiClient from a lot of unreachable code, and some code smells in ApiClient when using a proxy.
NodeAndExplorerDataSourceImpl shares its OkHttpClient between both ApiClient and ExplorerApiClient, as it is strongly advised to use OkHttpClient as a singleton (see OkHttpClient documentation). So instead of two new instances we only use one this way.
To get this even better, it should be possible to set the OkHttpClient to be used by `RestApiErgoClient` so that not a new one has to be spin up for every instantiation of it. I think the current proxy param of RestApiErgoClient should be replaced by a OkHttpClientBuilder param as this lets clients set proxy and many more settings like timeout etc. I just wanted to ask you on your opinion @aslesarenko because this means …
=> Cleanup ExplorerApiClient and ApiClient, share OkHttp instance

appkit/src/main/scala/org/ergoplatform/appkit/ColdErgoClient.scala, appkit/src/test/scala/org/ergoplatform/appkit/ErgoAuthSpec.scala, appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala, common/src/main/java/org/ergoplatform/appkit/Address.java, common/src/main/java/org/ergoplatform/appkit/AppkitProvingInterpreter.scala, common/src/main/java/org/ergoplatform/appkit/ErgoAuthUtils.java, common/src/main/java/org/ergoplatform/appkit/ErgoType.java, common/src/main/java/org/ergoplatform/appkit/ErgoValue.java, common/src/main/java/org/ergoplatform/appkit/JavaHelpers.scala, common/src/main/java/org/ergoplatform/appkit/Parameters.java, common/src/main/java/org/ergoplatform/appkit/SigmaProp.java, common/src/main/java/org/ergoplatform/appkit/SigmaPropInterpreter.scala, common/src/main/java/org/ergoplatform/appkit/Signature.java, lib-api/src/main/java/org/ergoplatform/appkit/BlockchainParameters.java, lib-api/src/main/java/org/ergoplatform/appkit/ErgoProver.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/ColdBlockchainContext.scala, lib-impl/src/main/java/org/ergoplatform/appkit/impl/ErgoProverImpl.scala
Adds ErgoAuthUtils utility methods for ErgoAuth ergoplatform/eips#53
On this occasion, ColdErgoClient was improved so that it does not need to be instantiated by using Explorer API model classes.
=> ErgoAuthUtils added for EIP-28

MIGRATION, appkit/src/test/resources/mockwebserver/node_responses/response_NodeInfo.json, lib-api/src/main/java/org/ergoplatform/appkit/BlockchainDataSource.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/BlockchainContextImpl.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/NodeAndExplorerDataSourceImpl.java, lib-impl/src/test/java/org/ergoplatform/appkit/impl/BlockchainContextImplTest.java
Users were reporting the following error when submitting transactions to the node:
>  "error" : 400,
>  "reason" : "bad.request",
>  "detail" : "Malformed transaction: Transaction outputs should have creationHeight not exceeding block height.  731399 <= >727346 is not true
Underlying cause is the node getting out of sync and having fullHeight and headersHeight diverge.
To minimize affected users in situations that are not as extreme as quoted above (sometimes the difference is only a single block), this PR changes BlockchainContextImpl to only use blocks known to fullHeight as preheaders for new transactions.
For this, BlockchainDataSource parameter has been added.
=> BlockchainContextImpl use only full headers to build transactions

appkit/src/test/scala/org/ergoplatform/appkit/AddressSpec.scala, common/src/main/java/org/ergoplatform/appkit/Address.java
This commit fixes that Testnet and Mainnet addresses were reported as equal by `Address.equals()`.
=> Fix Mainnet and Testnet Address being equal

appkit/src/test/scala/org/ergoplatform/appkit/AddressSpec.scala, common/src/main/java/org/ergoplatform/appkit/Address.java
Address.fromErgoValue and Address.toErgoValue come in handy when storing contracts as proposition bytes to boxes.
=> Address: add fromErgoValue and toErgoValue methods

common/src/main/java/org/ergoplatform/appkit/Parameters.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/NodeAndExplorerDataSourceImpl.java
Normally not necessary, but handy for problem investigations
=> Changed Testnet fee address, NodeAndExplorerDataSourceImpl: Add optional checkTransaction call

.github/workflows/release.yml
This skips the tests when building fat jar in release action, as they already run before for sonatype release.
=> Release action: Skip tests when building fat jar

appkit/src/test/scala/org/ergoplatform/appkit/AddressSpec.scala, common/src/main/java/org/ergoplatform/appkit/Address.java, common/src/main/java/org/ergoplatform/appkit/JavaHelpers.scala, common/src/main/java/org/ergoplatform/appkit/SigmaProp.java, java-client-generated/src/test/java/org/ergoplatform/explorer/client/DefaultApiTest.java
Adding convenience methods to convert from sigmastate SigmaProp to appkit's SigmaProp, and from SigmaBoolean to address.
This is needed when there is a SigmaProp saved in a box register.
=> Adding conversions from SigmaBoolean to Address

common/src/main/java/org/ergoplatform/appkit/ErgoType.java, common/src/main/java/org/ergoplatform/appkit/ErgoValue.java, common/src/main/java/org/ergoplatform/appkit/scalaapi/ErgoValueBuilder.scala, common/src/main/java/org/ergoplatform/appkit/scalaapi/Iso.scala, common/src/main/java/org/ergoplatform/appkit/scalaapi/package.scala, common/src/test/scala/org/ergoplatform/appkit/AppkitTestingCommon.scala, common/src/test/scala/org/ergoplatform/appkit/ErgoValueSpec.scala, common/src/test/scala/org/ergoplatform/appkit/TestingBase.scala, common/src/test/scala/org/ergoplatform/appkit/scalaapi/ErgoValueBuilderSpec.scala
Closes #184 
Implementation of generic builder to create ErgoValue instances with valid Java types from Scala.
=> Generic builder of ErgoValue for Scala

appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala, common/src/main/java/org/ergoplatform/appkit/InputBoxesSelectionException.java, lib-api/src/main/java/org/ergoplatform/appkit/BoxOperations.java
Recently several miners with small payout boxes expressed problems in the support channels sending ERG caused by too many input boxes. 
This expresses in the typical error indications:
* Error when submitting the transaction "too high cost"
* Very long loading time
* Timeout exceptions connecting Explorer and/or node
Too avoid all of these errors caused by too many needed input boxes, and to give a helpful error message to the users with a hint how many ERG and/or tokens can be sent with a certain set input boxes restriction, this adds an optional input box selection restriction to BoxOperations. When the amount of selected (not loaded) input boxes is exceeded, an exception is thrown that can be used to give the user helpful hints.
If the restriction is not set, the behaviour does not …
=> BoxOperations: property to restrict the amount of input boxes

java-client-generated/src/test/java/org/ergoplatform/restapi/client/TransactionsApiTest.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/PreHeaderBuilderImpl.java
Signing a transaction restricting the preHeader.timestamp to be at least a time between now and the last found block was not possible, because Appkit's PreHeader set its timestamp to the last found block.
This PR uses current system time, if higher than last found block.
=> Allow signing of transactions restricting preHeader.timestamp

.github/workflows/ci.yml
Due to problems on GitHub actions, or with explorer or node, this deactivates running the javaClientGenerated project in CI tests.
Excluding by tag was not possible because this module is a JUnit test runner. So only option I found is to list the other projects.
=> Excludes tests from javaClientGenerated

MIGRATION, lib-api/src/main/java/org/ergoplatform/appkit/BlockchainDataSource.java, lib-api/src/main/java/org/ergoplatform/appkit/InputBox.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/BlockchainContextImpl.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/InputBoxImpl.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/NodeAndExplorerDataSourceImpl.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/ScalaBridge.scala, lib-impl/src/test/java/org/ergoplatform/appkit/impl/BlockchainContextImplTest.java
Mgpai discovered that retrieving spent boxes to use them in box registers is currently not straightforward with appkit. This PR adds methods to make this task more easy for client code:
* `BlockchainDataSource#getBoxByIdWithSpent`
* `InputBox#toErgoValue`
* `InputBoxImpl` constructor for Explorer OutputInfo (used by `BlockchainDataSource#getBoxByIdWithSpent`)
=> Add methods to access spent boxes and save to registers

appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala, lib-api/src/main/java/org/ergoplatform/appkit/BoxOperations.java, lib-api/src/main/java/org/ergoplatform/appkit/InputBoxesValidator.scala, lib-api/src/main/java/org/ergoplatform/appkit/InputBoxesValidatorJavaHelper.scala, lib-impl/src/main/java/org/ergoplatform/appkit/impl/UnsignedTransactionBuilderImpl.scala
Closes #182
This removes usage of DefaultBoxSelector as we already select boxes either by `BoxOperations` or manually. Instead, we introduced `InputBoxesValidator` to do validations and change box calculation that the selector did and to be compatrible to `TransactionsBuilder`.
=> Use InputBoxesValidator instead of DefaultBoxSelector

appkit/src/test/scala/org/ergoplatform/appkit/TxBuilderSpec.scala, lib-api/src/main/java/org/ergoplatform/appkit/InputBoxesValidator.scala
Changes in #202 could end up in
java.lang.ClassCastException: class sigmastate.utils.Helpers$EitherOps cannot be cast to class scala.util.Either (sigmastate.utils.Helpers$EitherOps and scala.util.Either are in unnamed module of loader 'app')
instead of throwing NotEnoughCoinsForChangeException. This PR fixes this and adds the missing test case.
=> Fix ClassCastException introduced in #202

appkit/src/test/scala/org/ergoplatform/appkit/examples/DataInputsSpec.scala, lib-api/src/main/java/org/ergoplatform/appkit/InputBox.java, lib-impl/src/main/java/org/ergoplatform/appkit/impl/InputBoxImpl.java
This adds missing methods to `InputBox` interface:
* `getTransactionId`
* `getTransactionIndex`
=> InputBox add getTransactionId/getTransactionIndex methods
